version: 1.2.{build}
image: Visual Studio 2017
before_build:
- ps: dotnet restore
configuration:
  - Debug
  - Release
build:
  publish_nuget: true
  verbosity: minimal
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(appveyor_build_version)
deploy:
- provider: NuGet
  api_key:
    secure: 1TRtLMdrz0Uw+6VWQBSUG49Wf6zlHRzMk0FfIRDdw9+4ciMeAkDKcswpI8aAMbxc
  on:
    branch: master
    configuration: Release
